"use node";

import { v } from "convex/values";
import { action, internalAction } from "./_generated/server";
import { api, internal } from "./_generated/api";
import { execSync } from "child_process";
import * as fs from "fs";

const CADDY_CONTAINER = process.env.CADDY_CONTAINER || "caddy-proxy";
const CADDYFILE_PATH = process.env.CADDYFILE_PATH || "/data/berry-claw/Caddyfile";
const SERVER_IP = process.env.SERVER_IP || "127.0.0.1";

function isValidDomain(domain: string): boolean {
  return /^([a-z0-9]([a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,}$/i.test(domain);
}

export const setCustomDomain = action({
  args: {
    clawId: v.id("claws"),
    domain: v.string(),
  },
  returns: v.null(),
  handler: async (ctx, args): Promise<null> => {
    const domain = args.domain.trim().toLowerCase();
    if (!isValidDomain(domain)) {
      throw new Error("Invalid domain name");
    }

    const claw = await ctx.runQuery(api.claws.get, { clawId: args.clawId });
    if (!claw) throw new Error("Claw not found");

    await ctx.runMutation(internal.proxyMutations.updateClawDomain, {
      clawId: args.clawId,
      domain,
    });

    await ctx.runAction(internal.proxy.regenerateCaddyfile, {});

    await ctx.runMutation(internal.logs.create, {
      clawId: args.clawId,
      type: "config_update",
      message: `Custom domain set to ${domain}`,
    });

    return null;
  },
});

export const removeCustomDomain = action({
  args: { clawId: v.id("claws") },
  returns: v.null(),
  handler: async (ctx, args): Promise<null> => {
    const claw = await ctx.runQuery(api.claws.get, { clawId: args.clawId });
    if (!claw) throw new Error("Claw not found");

    await ctx.runMutation(internal.proxyMutations.updateClawDomain, {
      clawId: args.clawId,
      domain: null,
    });

    await ctx.runAction(internal.proxy.regenerateCaddyfile, {});

    await ctx.runMutation(internal.logs.create, {
      clawId: args.clawId,
      type: "config_update",
      message: "Custom domain removed",
    });

    return null;
  },
});

export const regenerateCaddyfile = internalAction({
  returns: v.null(),
  handler: async (ctx): Promise<null> => {
    const clawsWithDomains = await ctx.runQuery(
      internal.proxyMutations.listClawsWithDomains,
      {},
    );

    let caddyfile = "# Auto-generated by Berry Claw — do not edit manually\n\n";

    for (const claw of clawsWithDomains) {
      if (!claw.customDomain || claw.status === "removing") continue;
      caddyfile += `${claw.customDomain} {\n`;
      caddyfile += `  reverse_proxy ${SERVER_IP}:${claw.gatewayPort}\n`;
      caddyfile += `}\n\n`;
    }

    const dir = CADDYFILE_PATH.substring(0, CADDYFILE_PATH.lastIndexOf("/"));
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(CADDYFILE_PATH, caddyfile, "utf-8");

    try {
      execSync(
        `docker exec ${CADDY_CONTAINER} caddy reload --config /etc/caddy/Caddyfile`,
        { encoding: "utf-8", timeout: 15000 },
      );
    } catch {
      // Caddy container might not be running — OK for dev
    }

    return null;
  },
});
